### ISSUE TITLE
Change symfony/framework-bundle dependency to symfony/dependency-injection

### ISSUE THREAD

**Issue by quberok** [IndraGunawan/facade-bundle#1]
Hi!

Could you change `symfony/framework-bundle` dependency to `symfony/dependency-injection` please. It is not necessary to require `symfony/framework-bundle` in this case.

Thanks.

**Comment by IndraGunawan** [comment]
Do you have any use-case of using this bundle without `symfony/framework-bundle`

**Comment by IndraGunawan** [comment]
#3
